version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.6
    container_name: tool-registry-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: toolregistry
      MYSQL_USER: tooluser
      MYSQL_PASSWORD: toolpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5


  # Redis
  redis:
    image: redis:6.2-alpine
    container_name: tool-registry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5




volumes:
  mariadb-data:
  redis-data:
